#!/bin/bash
#
# Music Library Sync Script
#
# Synchronizes the user's Music directory with his directory
# on the server. 
#
#
#

# check that unison versions match
#

# run sync
#
unison-2.40 -ui text -perms 0 -fat -unicode utf8 ~/Music ssh://workstation/Music
