#!/bin/sh

if [ ! -f /etc/shake.d/.current_dir ]; then
	touch /etc/shake.d/.current_dir
fi

next=1
next_dir=
current_dir=$(cat /etc/shake.d/.current_dir)

# set next_dir to the first directory on the list
# and if current_dir is not initialized then initialize
# it to the first entry on the list
#
for d in $(cat /etc/shake.d/autoshake_dirs); do
	if [ "$current_dir" == "" ]; then
		current_dir=$d
	fi
	next_dir=$d
	break
done

# if the current_dir is not on the list then set
# it to the first item on the list
#
for d in $(cat /etc/shake.d/autoshake_dirs); do
	if [ "$current_dir" == "$d" ]; then
		next=0
	fi
done
if [ $next == 1 ]; then
	next=0
	current_dir=$next_dir
fi

# find the next directory on the list. If we reach the end of
# list or if the current directory was removed from the list
#
for d in $(cat /etc/shake.d/autoshake_dirs); do	
	if [ "$d" == "$current_dir" ]; then
		next=1
	elif [ $next == 1 ]; then
		next_dir=$d
		break
	fi
done

#echo "next: "$next_dir
#echo "curr: "$current_dir
#exit 0

# save $next_dir to /etc/shake.d/.current_dir to use it next
# time
#

# shake $current_dir nicely
#
echo "Shaking ${current_dir}..."
/usr/bin/nice -n 19 /usr/bin/shake $current_dir
echo $next_dir > /etc/shake.d/.current_dir
echo $(/bin/date) > /etc/shake.d/last_shake

